@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTg5YzJjZmRmMWIxNzY2MWIxZWUxNjgiLCJpYXQiOjE3ODc0MTMyMDEsImV4cCI6MTc4NzQ5OTYwMX0.L22ffMWwKHt40U1jYOti1TxiEMNZR7ISCPEXdeSjgfs
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

###
//LOGIN DO USUÁRIO
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

###
//RETORNA TODOS OS USUÁRIOS
GET {{baseUrl}}/user/allUser

###
//DELETA EM CASCATA TODOS OS USUÁRIOS
DELETE {{baseUrl}}/user/allUser

//Create for productCart
###
//ADICIONA UM PRODUTO AO USUÁRIO (ROTA PROTEGIDA)
POST {{baseUrl}}/productCart/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "currentCount": 1,
  "currentColor": "Black",
  "currentSize": "M",
  "productSlug": "refined-metal-0"
}

//REMOVE UM PRODUTO PELO ID DO PRODUTO (ROTA PROTEGIDA)
###
DELETE {{baseUrl}}/productCart/remove/6a89c2e1df1b17661b1ee169
Authorization: Bearer {{token}}

###
//REMOVE TODOS OS PRODUTOS DE TODOS OS USUÁRIOS (ROTA PROTEGIDA)
DELETE {{baseUrl}}/productCart/remove/
Authorization: Bearer {{token}}

### Request product by slug
###
//RETORNA UM PRODUTO PELO SLUG
GET {{baseUrl}}/products/refined-metal-0